// GENERATED by `npm run gen:java-protocol` (foreman/scripts/gen-java-protocol.ts) from foreman/src/protocol.ts.
// Do not edit by hand: change the zod schemas (or the JAVA table in the script) and regenerate.
// Hand-written behaviour (helpers, ack results without a schema) lives in ProtocolSupport.java.
package dev.agentcraft.client.foreman;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Java mirror of the Foreman protocol v1 (docs/protocol.md). Field names are exact. Optional fields are
 * nullable (boxed when numeric/boolean); required lists and maps are never null (normalised to empty). Unknown
 * JSON fields are ignored and unknown enum values map to {@code UNKNOWN}, so a newer Foreman never breaks the mod.
 */
public final class Protocol {
	public static final int VERSION = 1;

	private Protocol() {
	}

	/** Marker for protocol enums: wire value = lower-case constant name unless overridden; unknown values map to UNKNOWN. */
	public interface Wire {
		default String wire() {
			return ((Enum<?>) this).name().toLowerCase(Locale.ROOT);
		}
	}

	// ------------------------------------------------------------------ option labels

	public static final String MERGE = "Merge";
	public static final String REQUEST_CHANGES = "Request changes";
	public static final String REJECT = "Reject";
	public static final String ALLOW_ONCE = "Allow once";
	public static final String ALWAYS_ALLOW = "Always allow for this agent";
	public static final String DENY = "Deny";
	/** Merge decision option labels, in order. */
	public static final List<String> MERGE_OPTIONS = List.of(MERGE, REQUEST_CHANGES, REJECT);
	/** Permission decision option labels, in order. */
	public static final List<String> PERMISSION_OPTIONS = List.of(ALLOW_ONCE, ALWAYS_ALLOW, DENY);

	// ------------------------------------------------------------------ enums

	/** What the agent is doing right now; drives nameplate dot color, particles and animation. */
	public enum AgentState implements Wire, ProtocolSupport.AgentStateHelpers {
		IDLE, THINKING, READING, EDITING, RUNNING, TESTING, WAITING_USER, BLOCKED, DONE, ERROR, UNKNOWN
	}

	/** Where in the HQ the agent should walk to. `user` = next to the player / Decision Podium. */
	public enum Station implements Wire {
		DESK, LIBRARY, TERMINAL, TESTBENCH, MERGESTATION, MEETING, LOUNGE, USER, UNKNOWN
	}

	public enum AgentRole implements Wire {
		LEAD, WORKER, UNKNOWN
	}

	/**
	 * Task Wall column. `pr` = landed as a pull request that is still open (the Foreman watches it; see Task.pr):
	 * shown like review, labelled "PR open"; it becomes `done` when the PR is merged, `cancelled` when it is
	 * abandoned. `cancelled` tasks are kept for history but should not be shown on the wall.
	 */
	public enum TaskStatus implements Wire {
		TODO, DOING, REVIEW, PR, DONE, BLOCKED, CANCELLED, UNKNOWN
	}

	public enum CiStatus implements Wire {
		UNKNOWN, RUNNING, PASS, FAIL
	}

	public enum LogKind implements Wire {
		TEXT, TOOL, RESULT, ERROR, DIFF, UNKNOWN
	}

	public enum DecisionKind implements Wire {
		QUESTION, PERMISSION, MERGE, UNKNOWN
	}

	/** `cancelled` = became moot (agent stopped, task cancelled); render like answered. */
	public enum DecisionStatus implements Wire {
		OPEN, ANSWERED, CANCELLED, UNKNOWN
	}

	public enum GoalStatus implements Wire {
		PLANNING, ACTIVE, DONE, FAILED, CANCELLED, UNKNOWN
	}

	public enum FeedKind implements Wire {
		GOAL, PLAN, TASK, MESSAGE, DECISION, MERGE, CI, MEMORY, SYSTEM, ERROR, USER, UNKNOWN
	}

	public enum NotifyLevel implements Wire {
		INFO, WARN, NEED_USER, UNKNOWN
	}

	public enum WorktreeStatus implements Wire {
		ACTIVE, MERGED, ABANDONED, UNKNOWN
	}

	public enum BackendName implements Wire {
		SIM, CLAUDE, UNKNOWN
	}

	/** `failed` must be shown loudly (in-world banner): the claude backend cannot run. */
	public enum AuthStatus implements Wire {
		OK, FAILED, UNKNOWN, CHECKING
	}

	/**
	 * queued -&gt; designing (the design agent works) -&gt; checking (the Foreman re-runs the checker) -&gt;
	 * rendering (previews) -&gt; done; or failed / cancelled. done, failed and cancelled are final.
	 */
	public enum DesignStatus implements Wire, ProtocolSupport.DesignStatusHelpers {
		QUEUED, DESIGNING, CHECKING, RENDERING, DONE, FAILED, CANCELLED, UNKNOWN
	}

	/** style preset of a generated building (docs/HUB.md); `custom` = described only by the notes */
	public enum DesignStyle implements Wire {
		MODERN, CABIN, TOWNHOUSE, WORKSHOP, CAMPUS, CUSTOM, UNKNOWN
	}

	public enum DesignFeature implements Wire {
		PORCH, SKYLIGHTS, COURTYARD, BIG_WINDOWS, GARDEN, UNKNOWN
	}

	/**
	 * open: waiting for reviews; changes: a reviewer asked for changes (vote -5/-10, GitHub CHANGES_REQUESTED);
	 * approved: approved and nobody objects; merged / abandoned: closed on the host
	 */
	public enum PrStatus implements Wire {
		OPEN, CHANGES, APPROVED, MERGED, ABANDONED, UNKNOWN
	}

	/**
	 * build / status checks on the PR (Azure DevOps build policies, GitHub status checks); none = the PR has no
	 * checks
	 */
	public enum PrChecks implements Wire {
		PENDING, PASSING, FAILING, NONE, UNKNOWN
	}

	public enum DigestLineKind implements Wire {
		TASK_DONE, TASK_BLOCKED, TASK_ADDED, DECISION_WAITING, DECISION_ANSWERED, MERGED, PR_OPENED, PR_MERGED, PR_COMMENTS,
		MESSAGE, GOAL_DONE, UNKNOWN
	}

	/**
	 * How a setting is edited: bool toggle, int stepper (min/max), enum chips (options), string field, string list
	 * editor, model / effort picker (options), agent list (options = agent ids; ordered for claude.leads), map
	 * (read-only name -&gt; text), secretMap (a repository's `env`: value `{ NAME: "(set)" }`, names only, never
	 * values; config.set takes a partial update `{ NAME: "value" | null }`, null removes that variable), mcpServers
	 * (`claude.context.mcpServers`: value `[{ name, type: "stdio"|"http"|"sse", command?, args?, url?, envKeys }]`;
	 * an argument shows as "(hidden)" unless it clearly holds nothing secret (a bare flag, number, path or name, not
	 * after a credential flag such as --token, -H/--header, --key or --pat), URLs without credentials or query;
	 * config.set takes `[{ name, type, command?, args?, url?, env?: { NAME: "value" | null } } | { name, remove:
	 * true }]`, each an upsert or removal of that one server, the others unchanged; an argument or URL sent back
	 * exactly as shown keeps the stored original; a hidden or shortened one sent back in another place is refused)
	 */
	public enum SettingType implements Wire {
		BOOL("bool"), INT("int"), ENUM("enum"), STRING("string"), STRING_LIST("stringList"), MODEL("model"), EFFORT("effort"),
		AGENT_LIST("agentList"), MAP("map"), SECRET_MAP("secretMap"), MCP_SERVERS("mcpServers"), UNKNOWN("unknown");

		private final String wire;

		SettingType(String wire) {
			this.wire = wire;
		}

		@Override
		public String wire() {
			return wire;
		}
	}

	/**
	 * where the value comes from: config.json, a command-line flag, an AGENTCRAFT_* environment variable, or the
	 * built-in default
	 */
	public enum SettingSource implements Wire {
		FILE, FLAG, ENV, DEFAULT, UNKNOWN
	}

	public enum DiffFileStatus implements Wire {
		ADDED, MODIFIED, DELETED, RENAMED, UNKNOWN
	}

	public enum DiffLineKind implements Wire {
		ADD, DEL, CTX, UNKNOWN
	}

	// ------------------------------------------------------------------ entities and messages

	/**
	 * <ul>
	 * <li>{@code id}: stable lowercase id, e.g. "kit"</li>
	 * <li>{@code name}: display name, e.g. "Kit"</li>
	 * <li>{@code title}: short descriptive role from cast.json, e.g. "Backend tinkerer"</li>
	 * <li>{@code color}: agent color (scarf/badge/nameplate)</li>
	 * <li>{@code accent}: "#RRGGBB"</li>
	 * <li>{@code skin}: skin id -&gt; assets/agentcraft/textures/entity/agent/&lt;skin&gt;.png</li>
	 * <li>{@code state}: What the agent is doing right now; drives nameplate dot color, particles and
	 * animation.</li>
	 * <li>{@code activity}: one short line for the nameplate, e.g. "editing src/cli.ts" (&lt;= 48 chars)</li>
	 * <li>{@code station}: Where in the HQ the agent should walk to. `user` = next to the player / Decision
	 * Podium.</li>
	 * <li>{@code worktree}: id of the worktree the agent is working in (see Repo.worktrees)</li>
	 * <li>{@code active}: false = off shift (not on the current team, or stopped by the user); render idle in the
	 * lounge</li>
	 * </ul>
	 */
	public record Agent(String id, String name, AgentRole role, @Nullable String title, String color, @Nullable String accent, String skin,
		AgentState state, String activity, Station station, @Nullable String taskId, @Nullable String repoId, @Nullable String worktree,
		@Nullable Boolean paused, @Nullable Boolean active) implements ProtocolSupport.AgentHelpers {
		public Agent {
			name = ProtocolSupport.displayName(id, name);
			role = role == null ? AgentRole.UNKNOWN : role;
			color = color == null ? "#9C9488" : color;
			skin = skin == null ? id : skin;
			state = state == null ? AgentState.UNKNOWN : state;
			activity = activity == null ? "" : activity;
			station = station == null ? Station.UNKNOWN : station;
		}
	}

	/**
	 * <ul>
	 * <li>{@code ts}: epoch milliseconds</li>
	 * <li>{@code text}: may contain newlines; `diff` entries use unified +/- line prefixes</li>
	 * </ul>
	 */
	public record LogEntry(long ts, LogKind kind, String text) {
		public LogEntry {
			kind = kind == null ? LogKind.UNKNOWN : kind;
			text = text == null ? "" : text;
		}
	}

	/**
	 * <ul>
	 * <li>{@code open}: unresolved comment threads (system threads not counted)</li>
	 * <li>{@code new}: threads with comments the lead has not triaged yet</li>
	 * </ul>
	 */
	public record PrThreads(int open, @SerializedName("new") @Nullable Integer newCount) {
	}

	/**
	 * <ul>
	 * <li>{@code url}: the PR's web URL</li>
	 * <li>{@code id}: PR number on its host</li>
	 * <li>{@code branch}: source branch on the remote</li>
	 * <li>{@code target}: target branch on the remote</li>
	 * <li>{@code status}: open: waiting for reviews; changes: a reviewer asked for changes (vote -5/-10, GitHub
	 * CHANGES_REQUESTED); approved: approved and nobody objects; merged / abandoned: closed on the host</li>
	 * <li>{@code checks}: build / status checks on the PR (Azure DevOps build policies, GitHub status checks); none
	 * = the PR has no checks</li>
	 * <li>{@code updatedAt}: last successful poll of the host</li>
	 * </ul>
	 */
	public record TaskPr(String url, int id, @Nullable String host, @Nullable String branch, @Nullable String target, String status,
		@Nullable String checks, @Nullable PrThreads threads, long updatedAt) implements ProtocolSupport.TaskPrHelpers {
		public TaskPr {
			url = url == null ? "" : url;
			status = status == null ? "open" : status;
		}
	}

	/**
	 * <ul>
	 * <li>{@code id}: e.g. "t3"</li>
	 * <li>{@code status}: Task Wall column. `pr` = landed as a pull request that is still open (the Foreman watches
	 * it; see Task.pr): shown like review, labelled "PR open"; it becomes `done` when the PR is merged, `cancelled`
	 * when it is abandoned. `cancelled` tasks are kept for history but should not be shown on the wall.</li>
	 * <li>{@code assignee}: agent id</li>
	 * <li>{@code deps}: task ids that must be done before this one can start</li>
	 * <li>{@code priority}: higher = sooner; default 0</li>
	 * <li>{@code branch}: git branch, e.g. "agentcraft/kit/t2-tag-parser"</li>
	 * <li>{@code summary}: worker/lead summary of the result</li>
	 * <li>{@code pr}: the pull request this task landed as (repoSettings land "pr"), while it is watched and after
	 * it closed</li>
	 * <li>{@code createdBy}: agent id or "user"</li>
	 * <li>{@code createdAt}: epoch milliseconds</li>
	 * <li>{@code updatedAt}: epoch milliseconds</li>
	 * </ul>
	 */
	public record Task(String id, String title, @Nullable String description, TaskStatus status, @Nullable String assignee, List<String> deps,
		@Nullable String repoId, @Nullable String goalId, int priority, @Nullable String branch, @Nullable String worktree, CiStatus ci,
		@Nullable String blockedReason, @Nullable String summary, @Nullable TaskPr pr, @Nullable String createdBy, long createdAt, long updatedAt) {
		public Task {
			title = title == null ? id : title;
			status = status == null ? TaskStatus.UNKNOWN : status;
			deps = deps == null ? List.of() : List.copyOf(deps);
			ci = ci == null ? CiStatus.UNKNOWN : ci;
		}
	}

	/**
	 * <ul>
	 * <li>{@code option}: the chosen option label (one of Decision.options)</li>
	 * <li>{@code text}: free-text answer / feedback</li>
	 * <li>{@code ts}: epoch milliseconds</li>
	 * </ul>
	 */
	public record DecisionAnswer(@Nullable String option, @Nullable String text, long ts) {
	}

	/**
	 * <ul>
	 * <li>{@code id}: e.g. "d4"</li>
	 * <li>{@code agentId}: agent waiting on this decision</li>
	 * <li>{@code options}: button labels; first is the default/recommended choice</li>
	 * <li>{@code context}: extra detail, multi-line plain text. permission: why it asks, the cwd, and a line
	 * `"Always allow for this agent" covers: ...` (the scope of that choice). merge: summary + diff stat; after a
	 * refused merge the decision is open again and this ends with `Merge refused: &lt;reason&gt;`</li>
	 * <li>{@code status}: `cancelled` = became moot (agent stopped, task cancelled); render like answered.</li>
	 * <li>{@code repoId}: merge decisions: repo to request the diff from</li>
	 * <li>{@code worktree}: merge decisions: worktree to request the diff for</li>
	 * <li>{@code tool}: permission decisions: tool name, e.g. "Bash"</li>
	 * <li>{@code goalId}: the goal this decision is about (its task's goal, or the goal of the lead turn that
	 * asked); absent on older decisions and ones not tied to a goal</li>
	 * <li>{@code textAllowed}: false: only the options make sense (e.g. PR "Post"/"Skip", "Fold in"/"Leave it"):
	 * hide or disable free text; a `decision.answer` without a valid option is refused. Absent = true</li>
	 * <li>{@code createdAt}: epoch milliseconds</li>
	 * </ul>
	 */
	public record Decision(String id, String agentId, DecisionKind kind, String question, List<String> options, @Nullable String context,
		DecisionStatus status, @Nullable DecisionAnswer answer, @Nullable String taskId, @Nullable String repoId, @Nullable String worktree,
		@Nullable String tool, @Nullable String goalId, @Nullable Boolean textAllowed, long createdAt) implements ProtocolSupport.DecisionHelpers {
		public Decision {
			kind = kind == null ? DecisionKind.UNKNOWN : kind;
			question = question == null ? "" : question;
			options = options == null ? List.of() : List.copyOf(options);
			status = status == null ? DecisionStatus.UNKNOWN : status;
		}
	}

	/**
	 * <ul>
	 * <li>{@code id}: e.g. "kit-t2" — use as `worktree` in diff.request</li>
	 * <li>{@code base}: branch it was created from / will merge into</li>
	 * <li>{@code ahead}: commits on branch not on base</li>
	 * <li>{@code files}: files changed vs base (incl. uncommitted)</li>
	 * </ul>
	 */
	public record Worktree(String id, String agentId, @Nullable String taskId, String branch, String base, String path, WorktreeStatus status,
		int ahead, int files, int additions, int deletions) {
		public Worktree {
			status = status == null ? WorktreeStatus.UNKNOWN : status;
		}
	}

	public record RepoPrSettings(@Nullable String remote, @Nullable String branchPrefix, @Nullable Boolean draft, @Nullable Boolean squash) {
	}

	public record RepoPrReview(List<String> autoSeverities, @Nullable Integer maxRounds) {
		public RepoPrReview {
			autoSeverities = autoSeverities == null ? List.of() : List.copyOf(autoSeverities);
		}
	}

	/**
	 * <ul>
	 * <li>{@code land}: how approved work lands (repoSettings.land, default "merge")</li>
	 * <li>{@code baseBranch}: configured base branch (repoSettings.baseBranch)</li>
	 * <li>{@code ci}: configured test command (repoSettings.ci); absent = --ci or detected</li>
	 * <li>{@code setup}: worktree setup command (repoSettings.setup)</li>
	 * <li>{@code pr}: pull request options (repoSettings.pr)</li>
	 * <li>{@code protect}: paths never committed (repoSettings.protect)</li>
	 * <li>{@code roles}: agent id -&gt; the repository agent file that is its role here</li>
	 * <li>{@code subagents}: "repo": the repository's .claude/agents files are usable as subagents</li>
	 * <li>{@code prReview}: PR review triage (configured values, else the defaults)</li>
	 * <li>{@code envKeys}: names of the repoSettings.env variables (values are never sent)</li>
	 * </ul>
	 */
	public record RepoSettingsView(String land, @Nullable String baseBranch, @Nullable String ci, @Nullable String setup,
		@Nullable RepoPrSettings pr, List<String> protect, Map<String, String> roles, @Nullable String subagents, @Nullable RepoPrReview prReview,
		List<String> envKeys) {
		public RepoSettingsView {
			land = land == null ? "merge" : land;
			protect = protect == null ? List.of() : List.copyOf(protect);
			roles = roles == null ? Map.of() : Map.copyOf(roles);
			envKeys = envKeys == null ? List.of() : List.copyOf(envKeys);
		}
	}

	/**
	 * <ul>
	 * <li>{@code id}: e.g. "demo-app"</li>
	 * <li>{@code path}: absolute path of the user checkout</li>
	 * <li>{@code branch}: base branch agents branch from and merge into</li>
	 * <li>{@code head}: short sha of base branch</li>
	 * <li>{@code dirty}: user checkout has uncommitted tracked changes (merges are refused while dirty)</li>
	 * <li>{@code ci}: latest CI/test result across this repo</li>
	 * <li>{@code settings}: read-only view of the repository's config.json repoSettings (no secrets: env shows its
	 * keys only)</li>
	 * </ul>
	 */
	public record Repo(String id, String name, String path, String branch, @Nullable String head, boolean dirty, List<Worktree> worktrees,
		CiStatus ci, @Nullable RepoSettingsView settings) {
		public Repo {
			name = name == null ? id : name;
			worktrees = worktrees == null ? List.of() : List.copyOf(worktrees);
			ci = ci == null ? CiStatus.UNKNOWN : ci;
		}
	}

	/**
	 * <ul>
	 * <li>{@code id}: "shared/&lt;slug&gt;" or "&lt;agentId&gt;/&lt;slug&gt;"</li>
	 * <li>{@code scope}: "shared" or an agent id</li>
	 * <li>{@code body}: markdown</li>
	 * <li>{@code updated}: epoch milliseconds</li>
	 * <li>{@code author}: agent id or "user" that last wrote it</li>
	 * </ul>
	 */
	public record MemoryEntry(String id, String scope, String title, String body, long updated, @Nullable String author) {
		public MemoryEntry {
			scope = scope == null ? "shared" : scope;
			title = title == null ? id : title;
			body = body == null ? "" : body;
		}
	}

	/**
	 * <ul>
	 * <li>{@code id}: PR number on its host</li>
	 * <li>{@code status}: open: waiting for reviews; changes: a reviewer asked for changes (vote -5/-10, GitHub
	 * CHANGES_REQUESTED); approved: approved and nobody objects; merged / abandoned: closed on the host</li>
	 * </ul>
	 */
	public record GoalPr(@Nullable String taskId, @Nullable String url, int id, @Nullable String status) {
	}

	/**
	 * <ul>
	 * <li>{@code id}: e.g. "g1"</li>
	 * <li>{@code status}: planning (lead is planning) -&gt; active -&gt; done (every non-cancelled task
	 * merged/done); cancelled: every task was cancelled or rejected (back to active if the lead adds a task);
	 * failed: planning failed</li>
	 * <li>{@code leadId}: the lead running this goal (set at submit from the goal's repository: the lead of the
	 * building that has it). Absent = "marlow". Changes only while the goal is open: when its lead is released
	 * (lead.release / lead.sync / lead.releaseWorld) marlow takes it over; when a building is assigned its
	 * repository (lead.assign / lead.sync) that building's lead adopts it</li>
	 * <li>{@code repos}: every repository the goal touches: repoId first, then each task's repository in order of
	 * first appearance (kept up to date)</li>
	 * <li>{@code instructions}: standing instructions (goal.instructions): in the lead's prompts, appended to new
	 * task descriptions, and a section of every worker prompt for its tasks</li>
	 * <li>{@code planId}: memory entry id of the goal's plan note, once it exists</li>
	 * <li>{@code branch}: the user's branch the goal continues ("on &lt;branch&gt;:" prefix or goal.submit
	 * branch)</li>
	 * <li>{@code prs}: its tasks' pull requests (tasks with Task.pr), in task order</li>
	 * <li>{@code createdAt}: epoch milliseconds</li>
	 * <li>{@code updatedAt}: epoch milliseconds</li>
	 * </ul>
	 */
	public record Goal(String id, String text, double progress, GoalStatus status, @Nullable String repoId, @Nullable String leadId,
		@Nullable List<String> repos, @Nullable List<String> instructions, @Nullable String planId, @Nullable String branch,
		@Nullable List<GoalPr> prs, long createdAt, long updatedAt) implements ProtocolSupport.GoalHelpers {
		public Goal {
			text = text == null ? "" : text;
			status = status == null ? GoalStatus.UNKNOWN : status;
			repos = repos == null ? null : List.copyOf(repos);
			instructions = instructions == null ? null : List.copyOf(instructions);
			prs = prs == null ? null : List.copyOf(prs);
		}
	}

	/**
	 * <ul>
	 * <li>{@code ts}: epoch milliseconds</li>
	 * </ul>
	 */
	public record DigestLine(long ts, String kind, String text, @Nullable String taskId, @Nullable String agentId) {
		public DigestLine {
			kind = kind == null ? "message" : kind;
			text = text == null ? "" : text;
		}
	}

	/**
	 * <ul>
	 * <li>{@code text}: the goal's text</li>
	 * <li>{@code lines}: at most 30, oldest first (newest last); routine progress left out</li>
	 * </ul>
	 */
	public record GoalDigest(String goalId, @Nullable String text, @Nullable GoalStatus status, double progress, List<DigestLine> lines) {
		public GoalDigest {
			lines = lines == null ? List.of() : List.copyOf(lines);
		}
	}

	/**
	 * <ul>
	 * <li>{@code since}: epoch milliseconds</li>
	 * <li>{@code until}: epoch milliseconds</li>
	 * <li>{@code goals}: with goalId: that goal; without: every goal with something in the window</li>
	 * </ul>
	 */
	public record Digest(long since, long until, List<GoalDigest> goals) {
		public Digest {
			goals = goals == null ? List.of() : List.copyOf(goals);
		}
	}

	/**
	 * <ul>
	 * <li>{@code leadId}: a lead agent id, e.g. "ines"</li>
	 * <li>{@code building}: the building this lead leads; absent for "marlow" (home, repositories without a
	 * building, everything not tied to a repository)</li>
	 * <li>{@code repos}: repository ids of the building (a repository is in at most one building); empty for
	 * marlow</li>
	 * <li>{@code world}: the world (save folder name) the building is in; absent for marlow</li>
	 * <li>{@code lastSync}: when that world last talked to the Foreman (lead.sync / lead.assign / lead.release).
	 * Assignments of worlds not seen for `claude.leadWorldTtlDays` (default 14) are dropped</li>
	 * </ul>
	 */
	public record LeadAssignment(String leadId, @Nullable String building, List<String> repos, @Nullable String world, @Nullable Long lastSync) {
		public LeadAssignment {
			repos = repos == null ? List.of() : List.copyOf(repos);
		}
	}

	/**
	 * <ul>
	 * <li>{@code ts}: epoch milliseconds</li>
	 * <li>{@code agentId}: who it is about / from</li>
	 * <li>{@code to}: message recipient: agent id, "user" or "all"</li>
	 * <li>{@code goalId}: the goal the item is about (its tasks, its lead's turns for it, its PRs, goal messages);
	 * absent on older items and ones not tied to a goal</li>
	 * </ul>
	 */
	public record FeedItem(long ts, FeedKind kind, String text, @Nullable String agentId, @Nullable String to, @Nullable String goalId) {
		public FeedItem {
			kind = kind == null ? FeedKind.UNKNOWN : kind;
			text = text == null ? "" : text;
		}
	}

	/**
	 * <ul>
	 * <li>{@code id}: "five_hour", "seven_day", "seven_day_opus", "seven_day_sonnet", "overage"</li>
	 * <li>{@code label}: short label, e.g. "5h", "7d"</li>
	 * <li>{@code pct}: percent of the window used</li>
	 * <li>{@code resetsAt}: when the window resets</li>
	 * </ul>
	 */
	public record UsageWindow(String id, String label, double pct, @Nullable Long resetsAt) {
		public UsageWindow {
			id = id == null ? "" : id;
			label = label == null ? id : label;
		}
	}

	/**
	 * <ul>
	 * <li>{@code windows}: shortest window first</li>
	 * <li>{@code updatedAt}: epoch milliseconds</li>
	 * </ul>
	 */
	public record PlanUsage(List<UsageWindow> windows, long updatedAt) {
		public PlanUsage {
			windows = windows == null ? List.of() : List.copyOf(windows);
		}
	}

	/**
	 * <ul>
	 * <li>{@code reason}: usage: a usage limit was hit, or usage is above claude.usageReserve; auth: the login / API
	 * key failed (until a restart); offline: Claude could not be reached (retried with backoff)</li>
	 * <li>{@code until}: when the hold is expected to end (usage: the window resets; offline: the next retry)</li>
	 * <li>{@code message}: one line for a persistent HUD line</li>
	 * </ul>
	 */
	public record ForemanHold(String reason, @Nullable Long until, String message) {
		public ForemanHold {
			reason = reason == null ? "unknown" : reason;
			message = message == null ? "" : message;
		}
	}

	/**
	 * <ul>
	 * <li>{@code auth}: `failed` must be shown loudly (in-world banner): the claude backend cannot run.</li>
	 * <li>{@code message}: human-readable backend/auth status for the banner</li>
	 * <li>{@code account}: e.g. organization / plan when auth ok</li>
	 * <li>{@code speed}: sim: speed multiplier</li>
	 * <li>{@code showcase}: sim: holding a static showcase state (`--showcase` or `--showcase late`)</li>
	 * <li>{@code costUsd}: claude: estimated spend of this profile (sum over all sessions, survives restarts)</li>
	 * <li>{@code userName}: the person the team works for, as the agents address them (UI: "&lt;name&gt;
	 * answered")</li>
	 * <li>{@code usage}: claude.ai login: how much of the plan's usage windows is used (from the agents'
	 * sessions)</li>
	 * <li>{@code restartRequired}: config keys changed (config.set) that take effect only after a restart
	 * (`foreman.restart`); omitted when none</li>
	 * <li>{@code hold}: claude: the backend is holding new agent turns (usage limit or reserve, auth failure,
	 * offline); absent when nothing holds them. Running turns finish; queued work starts when the hold ends</li>
	 * </ul>
	 */
	public record ForemanStatus(String version, BackendName backend, AuthStatus auth, @Nullable String message, @Nullable String account,
		@Nullable Double speed, @Nullable Boolean showcase, @Nullable Double costUsd, @Nullable String userName, @Nullable PlanUsage usage,
		@Nullable List<String> restartRequired, @Nullable ForemanHold hold) {
		public ForemanStatus {
			version = version == null ? "?" : version;
			backend = backend == null ? BackendName.UNKNOWN : backend;
			auth = auth == null ? AuthStatus.UNKNOWN : auth;
			restartRequired = restartRequired == null ? null : List.copyOf(restartRequired);
		}
	}

	public record AgentLogs(String agentId, List<LogEntry> entries) {
		public AgentLogs {
			entries = entries == null ? List.of() : List.copyOf(entries);
		}
	}

	/**
	 * <ul>
	 * <li>{@code text}: line content without the +/-/space prefix</li>
	 * <li>{@code oldNo}: line number in base (del, ctx)</li>
	 * <li>{@code newNo}: line number in branch (add, ctx)</li>
	 * </ul>
	 */
	public record DiffLine(DiffLineKind kind, String text, @Nullable Integer oldNo, @Nullable Integer newNo) {
		public DiffLine {
			kind = kind == null ? DiffLineKind.UNKNOWN : kind;
			text = text == null ? "" : text;
		}
	}

	/**
	 * <ul>
	 * <li>{@code header}: e.g. "&#64;&#64; -12,6 +12,9 &#64;&#64; export function run"</li>
	 * </ul>
	 */
	public record DiffHunk(String header, int oldStart, int oldLines, int newStart, int newLines, List<DiffLine> lines) {
		public DiffHunk {
			header = header == null ? "" : header;
			lines = lines == null ? List.of() : List.copyOf(lines);
		}
	}

	/**
	 * <ul>
	 * <li>{@code oldPath}: renames only</li>
	 * </ul>
	 */
	public record DiffFile(String path, @Nullable String oldPath, DiffFileStatus status, boolean binary, int additions, int deletions,
		List<DiffHunk> hunks) {
		public DiffFile {
			status = status == null ? DiffFileStatus.UNKNOWN : status;
			hunks = hunks == null ? List.of() : List.copyOf(hunks);
		}
	}

	public record Size3(int x, int y, int z) {
	}

	/**
	 * <ul>
	 * <li>{@code kind}: single: one repo (wings must be 1); group: N repos, one wing each (wings &gt;= 2)</li>
	 * <li>{@code style}: style preset of a generated building (docs/HUB.md); `custom` = described only by the
	 * notes</li>
	 * <li>{@code materials}: agentcraft: the AgentCraft look built from vanilla blocks; vanilla: any vanilla look
	 * (both: AgentCraft blocks only for the station blocks)</li>
	 * <li>{@code maxSize}: the largest template allowed (x/z 9..128, y 6..48), e.g. from a marked plot</li>
	 * <li>{@code remix}: start from this blueprint id (bundled or user)</li>
	 * <li>{@code name}: display name; also names the blueprint id (gen_&lt;slug&gt;). Default: from the style</li>
	 * <li>{@code notes}: free text for the designer</li>
	 * <li>{@code outDir}: absolute `&lt;gameDir&gt;/agentcraft/blueprints` (the mod's user blueprint folder); any
	 * other path is refused</li>
	 * </ul>
	 */
	public record DesignRequest(String kind, int wings, String style, String materials, List<String> features, Size3 maxSize,
		@Nullable String remix, @Nullable String name, @Nullable String notes, String outDir) {
		public DesignRequest {
			kind = kind == null ? "single" : kind;
			style = style == null ? "" : style;
			materials = materials == null ? "agentcraft" : materials;
			features = features == null ? List.of() : List.copyOf(features);
			maxSize = maxSize == null ? new Size3(0, 0, 0) : maxSize;
			outDir = outDir == null ? "" : outDir;
		}
	}

	/**
	 * <ul>
	 * <li>{@code id}: e.g. "d7" (allocated from the same counter as decision ids, so never equal to one)</li>
	 * <li>{@code status}: queued -&gt; designing (the design agent works) -&gt; checking (the Foreman re-runs the
	 * checker) -&gt; rendering (previews) -&gt; done; or failed / cancelled. done, failed and cancelled are
	 * final.</li>
	 * <li>{@code step}: one line of progress, e.g. "running the checker (round 2)"</li>
	 * <li>{@code blueprintId}: done: the new blueprint id in outDir (gen_&lt;slug&gt;, gen_&lt;slug&gt;_2, ...)</li>
	 * <li>{@code size}: done: template size</li>
	 * <li>{@code previews}: done: absolute paths of the preview PNGs in outDir (empty when no renderer is
	 * available)</li>
	 * <li>{@code error}: failed: what went wrong (tail of the checker output)</li>
	 * <li>{@code createdAt}: epoch milliseconds</li>
	 * <li>{@code updatedAt}: epoch milliseconds</li>
	 * </ul>
	 */
	public record Design(String id, DesignRequest request, DesignStatus status, String step, @Nullable String blueprintId,
		@Nullable Size3 size, List<String> previews, @Nullable String error, long createdAt, long updatedAt) {
		public Design {
			status = status == null ? DesignStatus.UNKNOWN : status;
			step = step == null ? "" : step;
			previews = previews == null ? List.of() : List.copyOf(previews);
		}
	}

	/**
	 * <ul>
	 * <li>{@code key}: the config.json path, e.g. "claude.prWatch", "claude.agents.kit.model"; for a repository
	 * relative to its repoSettings entry, e.g. "land", "pr.draft", "roles.kit"</li>
	 * <li>{@code help}: one or two sentences for the user</li>
	 * <li>{@code group}: global: team, models, general, permissions, context, subagents, prs, usage; repository:
	 * landing, worktrees, agents, review</li>
	 * <li>{@code type}: How a setting is edited: bool toggle, int stepper (min/max), enum chips (options), string
	 * field, string list editor, model / effort picker (options), agent list (options = agent ids; ordered for
	 * claude.leads), map (read-only name -&gt; text), secretMap (a repository's `env`: value `{ NAME: "(set)" }`,
	 * names only, never values; config.set takes a partial update `{ NAME: "value" | null }`, null removes that
	 * variable), mcpServers (`claude.context.mcpServers`: value `[{ name, type: "stdio"|"http"|"sse", command?,
	 * args?, url?, envKeys }]`; an argument shows as "(hidden)" unless it clearly holds nothing secret (a bare flag,
	 * number, path or name, not after a credential flag such as --token, -H/--header, --key or --pat), URLs without
	 * credentials or query; config.set takes `[{ name, type, command?, args?, url?, env?: { NAME: "value" | null } }
	 * | { name, remove: true }]`, each an upsert or removal of that one server, the others unchanged; an argument or
	 * URL sent back exactly as shown keeps the stored original; a hidden or shortened one sent back in another place
	 * is refused)</li>
	 * <li>{@code options}: enum / model / effort / agentList / stringList choices (model: the Opus and Sonnet models
	 * in use and "default"; "default" clears the setting)</li>
	 * <li>{@code value}: the configured value (what config.json, a flag or the environment says now; may differ from
	 * what the running Foreman uses until a restart, see restartRequired)</li>
	 * <li>{@code default}: the value when nothing is configured</li>
	 * <li>{@code source}: where the value comes from: config.json, a command-line flag, an AGENTCRAFT_* environment
	 * variable, or the built-in default</li>
	 * <li>{@code live}: true: a change applies from the next turn / poll without a restart; false: after
	 * foreman.restart</li>
	 * <li>{@code overriddenBy}: the flag or variable that wins over config.json, e.g. "--lead-model" or
	 * "AGENTCRAFT_PR_WATCH": a change is written but has no effect while it is given</li>
	 * <li>{@code readOnly}: shown, never changed through config.set</li>
	 * </ul>
	 */
	public record SettingDef(String key, String label, String help, String group, SettingType type, @Nullable List<String> options,
		@Nullable Double min, @Nullable Double max, JsonElement value, @SerializedName("default") JsonElement defaultValue, SettingSource source,
		boolean live, @Nullable String overriddenBy, @Nullable Boolean readOnly) {
		public SettingDef {
			type = type == null ? SettingType.UNKNOWN : type;
			options = options == null ? null : List.copyOf(options);
			source = source == null ? SettingSource.UNKNOWN : source;
		}
	}

	/**
	 * `snapshot`: Full state. Sent in reply to every `hello`; the mod rebuilds its view from it.
	 *
	 * <ul>
	 * <li>{@code decisions}: open decisions plus the most recent answered ones</li>
	 * <li>{@code goal}: current (latest) goal</li>
	 * <li>{@code goals}: all goals, oldest first</li>
	 * <li>{@code feed}: most recent feed items, oldest first (&lt;= 200)</li>
	 * <li>{@code logs}: recent log tail per agent (&lt;= 60 entries each)</li>
	 * <li>{@code designs}: the most recent building designs (&lt;= 20), oldest first; queued/running ones always
	 * included</li>
	 * <li>{@code leads}: who leads what: marlow first (no building), then every assigned building lead (same as
	 * `leads.update`)</li>
	 * </ul>
	 */
	public record Snapshot(ForemanStatus foreman, List<Agent> agents, List<Task> tasks, List<Decision> decisions, List<Repo> repos,
		List<MemoryEntry> memory, @Nullable Goal goal, List<Goal> goals, List<FeedItem> feed, List<AgentLogs> logs, List<Design> designs,
		@Nullable List<LeadAssignment> leads) {
		public Snapshot {
			agents = agents == null ? List.of() : List.copyOf(agents);
			tasks = tasks == null ? List.of() : List.copyOf(tasks);
			decisions = decisions == null ? List.of() : List.copyOf(decisions);
			repos = repos == null ? List.of() : List.copyOf(repos);
			memory = memory == null ? List.of() : List.copyOf(memory);
			goals = goals == null ? List.of() : List.copyOf(goals);
			feed = feed == null ? List.of() : List.copyOf(feed);
			logs = logs == null ? List.of() : List.copyOf(logs);
			designs = designs == null ? List.of() : List.copyOf(designs);
			leads = leads == null ? null : List.copyOf(leads);
		}
	}

	/**
	 * `agent.upsert`: An agent was created or changed (state, station, activity, task...). Replace by `agent.id`.
	 */
	public record AgentUpsert(Agent agent) {
	}

	/** `agent.log`: New log lines for an agent monitor (append; keep a bounded tail). */
	public record AgentLog(String agentId, List<LogEntry> entries) {
		public AgentLog {
			entries = entries == null ? List.of() : List.copyOf(entries);
		}
	}

	/**
	 * `agent.say`: Speech bubble above the agent; also mirrored to the feed.
	 *
	 * <ul>
	 * <li>{@code to}: agent id, "user" or "all"; omitted = said to the room</li>
	 * <li>{@code ts}: epoch milliseconds</li>
	 * </ul>
	 */
	public record AgentSay(String agentId, String text, @Nullable String to, long ts) {
		public AgentSay {
			text = text == null ? "" : text;
		}
	}

	/** `task.upsert`: Task created or changed. Replace by `task.id`. */
	public record TaskUpsert(Task task) {
	}

	/** `decision.upsert`: Decision opened, answered or cancelled. Replace by `decision.id`. */
	public record DecisionUpsert(Decision decision) {
	}

	/** `repo.upsert`: Repo added or changed (worktrees, CI, head, dirty). Replace by `repo.id`. */
	public record RepoUpsert(Repo repo) {
	}

	/** `memory.upsert`: Memory entry written. Replace by `entry.id`. */
	public record MemoryUpsert(MemoryEntry entry) {
	}

	/**
	 * `goal.upsert`: Goal created or progress/status changed. Replace by `goal.id`; latest goal is current.
	 */
	public record GoalUpsert(Goal goal) {
	}

	/** `feed.add`: Append to the activity feed. */
	public record FeedAdd(FeedItem item) {
	}

	public record DiffStats(int files, int additions, int deletions) {
	}

	/**
	 * `diff`: Reply to `diff.request` (sent only to the requesting client). Structured unified diff of worktree vs
	 * base, including uncommitted changes.
	 *
	 * <ul>
	 * <li>{@code truncated}: true if very large files/hunks were cut</li>
	 * </ul>
	 */
	public record Diff(String requestId, String repoId, String worktree, @Nullable String base, @Nullable String branch, List<DiffFile> files,
		DiffStats stats, boolean truncated, @Nullable String error) {
		public Diff {
			files = files == null ? List.of() : List.copyOf(files);
			stats = stats == null ? new DiffStats(0, 0, 0) : stats;
		}
	}

	/**
	 * `notify`: Toast/banner for the player. `need_user` = a decision is waiting (play a bell).
	 *
	 * <ul>
	 * <li>{@code ts}: epoch milliseconds</li>
	 * </ul>
	 */
	public record Notify(NotifyLevel level, String text, @Nullable String decisionId, long ts) {
		public Notify {
			level = level == null ? NotifyLevel.UNKNOWN : level;
			text = text == null ? "" : text;
		}
	}

	/**
	 * `design.upsert`: A building design was requested or progressed (status, step) or finished. Replace by
	 * `design.id`. On `done` the blueprint files are already in `request.outDir`: reload blueprints.
	 */
	public record DesignUpsert(Design design) {
	}

	/** `foreman.status`: Backend/auth status changed (banner). */
	public record ForemanStatusMsg(ForemanStatus status) {
	}

	/**
	 * `leads.update`: Lead assignments changed (lead.assign / lead.release / lead.sync, or the Foreman dropped a
	 * lead that is no longer configured). Full list; also in `snapshot.leads`. A lead agent (role `lead`) other than
	 * marlow is in `snapshot.agents` and gets `agent.upsert` only while it is assigned; a released lead gets one
	 * last `agent.upsert` (active=false, lounge) and should walk home and despawn.
	 *
	 * <ul>
	 * <li>{@code leads}: the full list (replace): marlow first, then each assigned building lead</li>
	 * </ul>
	 */
	public record LeadsUpdate(List<LeadAssignment> leads) {
		public LeadsUpdate {
			leads = leads == null ? List.of() : List.copyOf(leads);
		}
	}

	/**
	 * `config.changed`: config.set changed config.json (any client). Clients showing settings fetch them again
	 * (`config.get`).
	 *
	 * <ul>
	 * <li>{@code keys}: the keys config.set changed (repository keys as "repo:&lt;repoId&gt;:&lt;key&gt;")</li>
	 * <li>{@code restartRequired}: every changed key still waiting for a restart (the full list, same as
	 * foreman.status.restartRequired)</li>
	 * </ul>
	 */
	public record ConfigChanged(List<String> keys, List<String> restartRequired) {
		public ConfigChanged {
			keys = keys == null ? List.of() : List.copyOf(keys);
			restartRequired = restartRequired == null ? List.of() : List.copyOf(restartRequired);
		}
	}

	/**
	 * `ack`: Reply to any client message that carried an `id`.
	 *
	 * <ul>
	 * <li>{@code re}: the `id` of the client message being acknowledged</li>
	 * <li>{@code result}: e.g. {goalId} for goal.submit, {repoId} for repo.add</li>
	 * </ul>
	 */
	public record Ack(String re, boolean ok, @Nullable String error, @Nullable JsonObject result) {
	}

	/** `error`: A client message was invalid or failed (also sent as ack.ok=false when it had an id). */
	public record ErrorMsg(String message, @Nullable String re) {
	}

	/**
	 * `hello`: First message after connecting. The Foreman replies with `snapshot`, then streams upserts.
	 *
	 * <ul>
	 * <li>{@code client}: "mod" | "cli" | ... (informational)</li>
	 * <li>{@code token}: the client token: the contents of the file the run file names in `tokenFile`
	 * (`&lt;dataDir&gt;/client.token`, new on every Foreman start). Without a valid token the connection is
	 * read-only: snapshot and events, and only `hello`, `diff.request`, `goal.digest` and `agent.logs.request`;
	 * every other message is refused (`ack.ok` false, "read-only connection: no client token")</li>
	 * </ul>
	 */
	public record HelloMsg(String modVersion, int protocol, @Nullable String client, @Nullable String token) {
	}

	/**
	 * `goal.submit`: New goal for the lead (console: plain text). Acked with `{goalId}`.
	 *
	 * <ul>
	 * <li>{@code repoId}: defaults to repos[0], else the only/most recently added repo</li>
	 * <li>{@code repos}: the repositories the goal is for (e.g. a group building's); the first becomes repoId when
	 * repoId is absent. The goal's lead is the lead of repoId</li>
	 * <li>{@code branch}: continue this branch of the user's (same as an "on &lt;branch&gt;:" prefix; wins over
	 * it)</li>
	 * <li>{@code instructions}: standing instructions from the start (see goal.instructions)</li>
	 * </ul>
	 */
	public record GoalSubmitMsg(String text, @Nullable String repoId, @Nullable List<String> repos, @Nullable String branch,
		@Nullable List<String> instructions) {
		public GoalSubmitMsg {
			repos = repos == null ? null : List.copyOf(repos);
			instructions = instructions == null ? null : List.copyOf(instructions);
		}
	}

	/**
	 * `goal.message`: A message to the goal's lead about that goal. It runs as a turn of the lead's session for the
	 * goal (queued behind its other work; also for done/cancelled goals). The user's message and the lead's replies
	 * arrive as `feed.add` items with kind `message` and `goalId`. Acked with `{goalId, leadId}`.
	 */
	public record GoalMessageMsg(String goalId, String text) {
	}

	/**
	 * `goal.instructions`: Replace the goal's standing instructions (`Goal.instructions`). A change is sent to the
	 * lead as a goal message. Acked with `{goalId, changed}`.
	 *
	 * <ul>
	 * <li>{@code instructions}: the full list (replace); blank lines are dropped</li>
	 * </ul>
	 */
	public record GoalInstructionsMsg(String goalId, List<String> instructions) {
		public GoalInstructionsMsg {
			instructions = instructions == null ? List.of() : List.copyOf(instructions);
		}
	}

	/**
	 * `goal.plan`: Write the goal's plan note as the user (creates it when missing; `memory.upsert`, `Goal.planId`),
	 * then send the lead a goal message with a unified diff of the change. Acked with `{goalId, planId, changed}`.
	 *
	 * <ul>
	 * <li>{@code body}: the plan note's new markdown body</li>
	 * </ul>
	 */
	public record GoalPlanMsg(String goalId, String body) {
	}

	/**
	 * `goal.cancel`: Cancel every open task of the goal (running workers stop, worktrees and branches kept, open
	 * decisions withdrawn) and set it `cancelled`. Refused for a done goal. Acked with `{goalId, cancelled:
	 * [taskIds]}`.
	 */
	public record GoalCancelMsg(String goalId) {
	}

	/**
	 * `goal.digest`: What happened since `since` ("since you were away"). Acked with a `Digest` as `result`
	 * (`{since, until, goals}`); built from the feed, tasks and decisions, no model call.
	 *
	 * <ul>
	 * <li>{@code goalId}: one goal; omitted = every goal with activity in the window</li>
	 * <li>{@code since}: epoch milliseconds</li>
	 * </ul>
	 */
	public record GoalDigestMsg(@Nullable String goalId, long since) {
	}

	/**
	 * `repo.remove`: Unregister a repository. Refused while it has open tasks (not done/cancelled) or a goal that is
	 * still planning. Worktrees, branches and lead assignments are left alone; there is no removal broadcast: other
	 * clients see it in their next snapshot. Acked with `{repoId}`.
	 */
	public record RepoRemoveMsg(String repoId) {
	}

	/**
	 * `user.message`: Message an agent (console: `&#64;name text`) or everyone.
	 *
	 * <ul>
	 * <li>{@code to}: agent id or "all". With "all", a leading "&#64;name" in text routes to that agent.</li>
	 * </ul>
	 */
	public record UserMessageMsg(String to, String text) {
	}

	/**
	 * `decision.answer`: Answer an open decision. Merge decisions: option "Merge" merges, "Request changes" sends
	 * `text` back to the worker, "Reject" abandons the branch.
	 *
	 * <ul>
	 * <li>{@code option}: option label (preferred) or 0-based index into Decision.options</li>
	 * <li>{@code text}: free text (questions) or feedback (merge "Request changes")</li>
	 * </ul>
	 */
	public record DecisionAnswerMsg(String decisionId, @Nullable JsonElement option, @Nullable String text) {
	}

	/**
	 * `task.action`: Steer a task from the Task Wall.
	 *
	 * <ul>
	 * <li>{@code arg}: reassign: agent id; prioritize: integer priority (default: bump to top)</li>
	 * </ul>
	 */
	public record TaskActionMsg(String taskId, String action, @Nullable String arg) {
	}

	/**
	 * `agent.action`: Pause/resume/stop an agent, or spawn (activate) an off-shift worker.
	 *
	 * <ul>
	 * <li>{@code action}: pause: abort the current turn, keep the task (open questions are withdrawn); resume
	 * continues it. stop: off shift (active=false) until resume/spawn: turn aborted, open questions/permission
	 * prompts withdrawn, its doing tasks go back to the board and the next worker continues from the same branch.
	 * spawn: bring an off-shift agent onto the team.</li>
	 * <li>{@code arg}: spawn: optional task id to assign to the agent</li>
	 * </ul>
	 */
	public record AgentActionMsg(String agentId, String action, @Nullable String arg) {
	}

	/**
	 * `diff.request`: Ask for the structured diff of a worktree. Answered with `diff` (same requestId).
	 *
	 * <ul>
	 * <li>{@code worktree}: worktree id (e.g. "kit-t2"); an agent id resolves to that agent's current worktree</li>
	 * </ul>
	 */
	public record DiffRequestMsg(String requestId, String repoId, String worktree) {
	}

	/** `repo.add`: Register a local git repo (console: `/repo add &lt;path&gt;`). */
	public record RepoAddMsg(String path) {
	}

	/**
	 * `design.request`: Design a new building blueprint (hub: Buildings -&gt; Design new). Acked with `{designId}`;
	 * progress arrives as `design.upsert`. One design runs at a time; later ones queue.
	 */
	public record DesignRequestMsg(DesignRequest request) {
	}

	/**
	 * `design.cancel`: Cancel a queued or running design (the design agent's turn is stopped; nothing is written to
	 * outDir).
	 */
	public record DesignCancelMsg(String designId) {
	}

	/**
	 * `pr.refresh`: Poll the pull request(s) of tasks in status `pr` now instead of at the next interval (claude
	 * backend with PR watching on). Changes arrive as `task.upsert`.
	 *
	 * <ul>
	 * <li>{@code taskId}: the task whose PR to poll now; omitted = every task in status `pr`</li>
	 * </ul>
	 */
	public record PrRefreshMsg(@Nullable String taskId) {
	}

	/**
	 * `lead.assign`: A building holding repositories was placed (or its repositories changed). Acked with
	 * `{leadId}`. Idempotent: the same `building` keeps its lead and gets its repos updated. A new building takes
	 * the first free lead in `claude.leads` order; when none is free the ack says `{leadId: "marlow", overflow:
	 * true}` and nothing is stored. A repository listed here leaves any other building that had it; a building left
	 * with no repository (here with `repos: []`, or because its last one moved) frees its lead. Open goals (planning
	 * / active) whose repository (`repoId`, else `repos[0]`) is in the building move to its lead (feed line per
	 * goal); new goals in these repositories go to that lead too.
	 *
	 * <ul>
	 * <li>{@code building}: "&lt;worldId&gt;/&lt;buildingId&gt;" (worldId = the save folder name, so two worlds on
	 * one Foreman do not collide)</li>
	 * <li>{@code repos}: repository ids the building holds</li>
	 * </ul>
	 */
	public record LeadAssignMsg(String building, List<String> repos) {
		public LeadAssignMsg {
			repos = repos == null ? List.of() : List.copyOf(repos);
		}
	}

	/**
	 * `lead.release`: The building was removed. Acked with `{}` (also for a building that has no lead). Its lead
	 * goes off shift; its open goals move to marlow (feed line; marlow gets the plan note when it takes over).
	 *
	 * <ul>
	 * <li>{@code building}: "&lt;worldId&gt;/&lt;buildingId&gt;" (worldId = the save folder name, so two worlds on
	 * one Foreman do not collide)</li>
	 * </ul>
	 */
	public record LeadReleaseMsg(String building) {
	}

	/**
	 * `config.get`: The editable settings (hub Team / Settings tabs, Repos "Edit settings"). Acked with `{file,
	 * settings: SettingDef[]}`: the global settings, or with `repoId` that repository's repoSettings. Never contains
	 * secret values: environment values, tokens, MCP server env values or headers, credential-looking arguments, URL
	 * credentials or queries.
	 *
	 * <ul>
	 * <li>{@code repoId}: that repository's repoSettings instead of the global settings</li>
	 * </ul>
	 */
	public record ConfigGetMsg(@Nullable String repoId) {
	}

	/**
	 * <ul>
	 * <li>{@code value}: the new value; null (or "default" for a model / per-agent effort) removes the key from
	 * config.json, back to the default; for a secretMap or mcpServers setting a partial update (see
	 * SettingType)</li>
	 * </ul>
	 */
	public record ConfigChange(String key, JsonElement value) {
	}

	/**
	 * `config.set`: Change settings. Every change is validated first (all or nothing: one bad change refuses the
	 * lot, `ack.error` lists the problems), then config.json is written atomically (previous file kept as
	 * `config.json.bak`; unknown keys, other sections and key order kept), `live` keys apply at once (from the next
	 * turn / poll), and the ack is `{applied: [key], restartRequired: [key], overridden: [{key, by}]}` (a key a flag
	 * or variable also sets is written but stays overridden). Then `config.changed` is broadcast and
	 * `foreman.status.restartRequired` updated. Repository changes go to `repoSettings[&lt;the repo's path as
	 * config.json spells it, else its absolute path&gt;]`. Secret values sent here (`secretMap`, `mcpServers` env)
	 * are never echoed in the ack, an error, `config.changed` or a log line.
	 *
	 * <ul>
	 * <li>{@code repoId}: change that repository's repoSettings</li>
	 * </ul>
	 */
	public record ConfigSetMsg(@Nullable String repoId, List<ConfigChange> changes) {
		public ConfigSetMsg {
			changes = changes == null ? List.of() : List.copyOf(changes);
		}
	}

	/**
	 * `foreman.restart`: Restart the Foreman with the same arguments, environment and working directory (except
	 * `--reset`, `--goal` and `--autostart`). Acked with `{}` first; then the server closes (clients see the
	 * connection drop and reconnect), running turns are interrupted and resumed on start (`resumeOnStart`), and a
	 * new Foreman process (new pid, new client token: read the run file again) takes over the same port.
	 */
	public record ForemanRestartMsg() {
	}

	/**
	 * `agent.logs.request`: Older entries of an agent's log (the full history the Foreman stored, across one
	 * rotation: `logs/&lt;agent&gt;.jsonl` and `&lt;agent&gt;.1.jsonl`), for a scrollable log view; read-only
	 * (allowed without the client token). Acked with `{agentId, entries: LogEntry[], more}`: `entries` oldest first,
	 * all older than `before`; `more` = older entries exist (ask again with `before` = the first entry's `ts`). An
	 * unknown agent is refused.
	 *
	 * <ul>
	 * <li>{@code before}: only entries older than this (the `ts` of the oldest entry the client has); omitted = the
	 * newest</li>
	 * <li>{@code limit}: at most this many entries (default 200); entries sharing the oldest one's `ts` are never
	 * split, so a page can be slightly longer</li>
	 * </ul>
	 */
	public record AgentLogsRequestMsg(String agentId, @Nullable Long before, @Nullable Integer limit) {
	}

	/**
	 * `repo.agents`: The repository's Claude Code agent files (`.claude/agents/*.md` in its checkout), for the roles
	 * picker. Acked with `{agents: [{id, name, path, description?, model?}]}`: `id` is the file name without `.md`
	 * (the value to store in `roles.&lt;agent&gt;`), `name` the front matter name (else the id), `path`
	 * repo-relative.
	 */
	public record RepoAgentsMsg(String repoId) {
	}

	/**
	 * <ul>
	 * <li>{@code building}: "&lt;worldId&gt;/&lt;buildingId&gt;" (worldId = the save folder name, so two worlds on
	 * one Foreman do not collide)</li>
	 * </ul>
	 */
	public record LeadSyncBuilding(String building, List<String> repos) {
		public LeadSyncBuilding {
			repos = repos == null ? List.of() : List.copyOf(repos);
		}
	}

	/**
	 * `lead.sync`: Sent by the mod on connect for its world: every `"&lt;world&gt;/..."` building not in the list is
	 * released first, then each listed building is assigned (as `lead.assign`). Acked with `{leads}` (building -&gt;
	 * lead id). Also records the world's `lastSync`.
	 *
	 * <ul>
	 * <li>{@code world}: the world id (save folder name)</li>
	 * <li>{@code buildings}: every building of that world that holds repositories</li>
	 * </ul>
	 */
	public record LeadSyncMsg(String world, List<LeadSyncBuilding> buildings) {
		public LeadSyncMsg {
			buildings = buildings == null ? List.of() : List.copyOf(buildings);
		}
	}

	/**
	 * `lead.releaseWorld`: Release every lead held by buildings of another world (hub Team tab "Release" next to a
	 * world in `leads.update` that is not the current one). Acked with `{released: [leadId]}`; their open goals move
	 * to marlow as with `lead.release`. Worlds that have not synced for `claude.leadWorldTtlDays` (default 14; 0 =
	 * never) are released automatically at start and daily.
	 *
	 * <ul>
	 * <li>{@code world}: the world id (save folder name) whose leads to release</li>
	 * </ul>
	 */
	public record LeadReleaseWorldMsg(String world) {
	}

	// ------------------------------------------------------------------ message types

	/** Foreman -> mod: message {@code type} -> record (the envelope fields v, type, id are not part of the records). */
	public static final Map<String, Class<? extends Record>> SERVER_MESSAGES = Map.ofEntries(
		Map.entry("snapshot", Snapshot.class),
		Map.entry("agent.upsert", AgentUpsert.class),
		Map.entry("agent.log", AgentLog.class),
		Map.entry("agent.say", AgentSay.class),
		Map.entry("task.upsert", TaskUpsert.class),
		Map.entry("decision.upsert", DecisionUpsert.class),
		Map.entry("repo.upsert", RepoUpsert.class),
		Map.entry("memory.upsert", MemoryUpsert.class),
		Map.entry("goal.upsert", GoalUpsert.class),
		Map.entry("feed.add", FeedAdd.class),
		Map.entry("diff", Diff.class),
		Map.entry("notify", Notify.class),
		Map.entry("design.upsert", DesignUpsert.class),
		Map.entry("foreman.status", ForemanStatusMsg.class),
		Map.entry("leads.update", LeadsUpdate.class),
		Map.entry("config.changed", ConfigChanged.class),
		Map.entry("ack", Ack.class),
		Map.entry("error", ErrorMsg.class));

	/** Mod -> Foreman: message {@code type} -> record (the envelope fields v, type, id are not part of the records). */
	public static final Map<String, Class<? extends Record>> CLIENT_MESSAGES = Map.ofEntries(
		Map.entry("hello", HelloMsg.class),
		Map.entry("goal.submit", GoalSubmitMsg.class),
		Map.entry("goal.message", GoalMessageMsg.class),
		Map.entry("goal.instructions", GoalInstructionsMsg.class),
		Map.entry("goal.plan", GoalPlanMsg.class),
		Map.entry("goal.cancel", GoalCancelMsg.class),
		Map.entry("goal.digest", GoalDigestMsg.class),
		Map.entry("repo.remove", RepoRemoveMsg.class),
		Map.entry("user.message", UserMessageMsg.class),
		Map.entry("decision.answer", DecisionAnswerMsg.class),
		Map.entry("task.action", TaskActionMsg.class),
		Map.entry("agent.action", AgentActionMsg.class),
		Map.entry("diff.request", DiffRequestMsg.class),
		Map.entry("repo.add", RepoAddMsg.class),
		Map.entry("design.request", DesignRequestMsg.class),
		Map.entry("design.cancel", DesignCancelMsg.class),
		Map.entry("pr.refresh", PrRefreshMsg.class),
		Map.entry("lead.assign", LeadAssignMsg.class),
		Map.entry("lead.release", LeadReleaseMsg.class),
		Map.entry("config.get", ConfigGetMsg.class),
		Map.entry("config.set", ConfigSetMsg.class),
		Map.entry("foreman.restart", ForemanRestartMsg.class),
		Map.entry("agent.logs.request", AgentLogsRequestMsg.class),
		Map.entry("repo.agents", RepoAgentsMsg.class),
		Map.entry("lead.sync", LeadSyncMsg.class),
		Map.entry("lead.releaseWorld", LeadReleaseWorldMsg.class));
}
